//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string ShortDesc { get; set; }
        public string ArticleContent { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Keyword { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> ArticleGroupID { get; set; }
    
        public virtual ArticleGroup ArticleGroup { get; set; }
    }
}
