//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomProduct()
        {
            this.CustomeProsuctsImages = new HashSet<CustomeProsuctsImage>();
            this.ProductReports = new HashSet<ProductReport>();
        }
    
        public int id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Descriptions { get; set; }
        public string PageContent { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomeProsuctsImage> CustomeProsuctsImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReport> ProductReports { get; set; }
    }
}
