//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertInfo
    {
        public int id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string NationalCode { get; set; }
        public string BirthDate { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
