//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int id { get; set; }
        public int AlbumId { get; set; }
        public string Comments { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> MediaType { get; set; }
        public string TumbImage { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual MediaType MediaType1 { get; set; }
    }
}
