//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainSlider
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<int> TextColorId { get; set; }
        public string Image { get; set; }
        public Nullable<int> ActionColorId1 { get; set; }
        public Nullable<int> ActionColorId2 { get; set; }
        public string ActionTitle1 { get; set; }
        public string ActionTitle2 { get; set; }
        public string LinkAction1 { get; set; }
        public string LinkAction2 { get; set; }
        public Nullable<int> AlignId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Bottom { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
