//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string DirectUrl { get; set; }
        public Nullable<bool> OpenInNew { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual MenuType MenuType { get; set; }
    }
}
