//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PegeID { get; set; }
        public string Title { get; set; }
        public string PageName { get; set; }
        public string UniqID { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<int> UesrID { get; set; }
        public string PageContent { get; set; }
        public string ImageUrl { get; set; }
        public string ImageTitle { get; set; }
        public string ImageDesc { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string DirectLink { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public string Keywords { get; set; }
        public string ShortDesc { get; set; }
    }
}
