//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductReport()
        {
            this.ProductReportAnswers = new HashSet<ProductReportAnswer>();
            this.ProductReportExperts = new HashSet<ProductReportExpert>();
            this.ProductReportDocs = new HashSet<ProductReportDoc>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string AdminId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ProductReportStatu ProductReportStatu { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReportAnswer> ProductReportAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReportExpert> ProductReportExperts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReportDoc> ProductReportDocs { get; set; }
        public virtual CustomProduct CustomProduct { get; set; }
    }
}
