//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecureArticle
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public string ArticleContent { get; set; }
    }
}
