//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendSM
    {
        public long id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<bool> IsNotEnded { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
    }
}
