//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetting
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string MetaKeyWords { get; set; }
        public string MetaDescription { get; set; }
        public string SiteIcone { get; set; }
        public string MailSMPT { get; set; }
        public string MailPort { get; set; }
        public string MailUser { get; set; }
        public string MailPassword { get; set; }
        public string MailForm { get; set; }
        public string Disclaimer { get; set; }
        public string FooterText { get; set; }
        public string FooterAbout { get; set; }
        public Nullable<bool> FactorActive { get; set; }
        public Nullable<bool> VAT { get; set; }
        public Nullable<long> VatPercent { get; set; }
        public Nullable<long> SendBoxingPrice { get; set; }
        public Nullable<long> SendTaxPrice { get; set; }
        public Nullable<long> SendInsurancePrice { get; set; }
        public Nullable<long> SentVatPrice { get; set; }
        public Nullable<bool> SendBirthDateGift { get; set; }
        public Nullable<long> BirthDateGiftPrice { get; set; }
        public Nullable<int> ProfitPercentCount { get; set; }
        public Nullable<int> ProfitPercent { get; set; }
    }
}
