//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TasksList()
        {
            this.TaskDocs = new HashSet<TaskDoc>();
            this.TaskExperts = new HashSet<TaskExpert>();
            this.TaskAnswers = new HashSet<TaskAnswer>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<int> TimeRequired { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string AdminId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool SendSMSAlarm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDoc> TaskDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskExpert> TaskExperts { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAnswer> TaskAnswers { get; set; }
    }
}
