//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAnwerDoc
    {
        public int id { get; set; }
        public Nullable<int> TaskAnswerId { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
    
        public virtual TaskAnswer TaskAnswer { get; set; }
    }
}
