//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserLogin
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public int Code { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string UserId { get; set; }
    }
}
