//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWBagTransaction
    {
        public Nullable<System.DateTime> dateInsert { get; set; }
        public Nullable<int> BagId { get; set; }
        public int id { get; set; }
        public Nullable<long> AddPrice { get; set; }
        public string Descriptions { get; set; }
        public Nullable<long> MinusPrice { get; set; }
        public Nullable<long> BagPrice { get; set; }
        public string userId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string persiandate { get; set; }
    }
}
