//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWTaskUser
    {
        public string UseId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int id { get; set; }
    }
}
