//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWUserInfo
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string CodeMelli { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> IntroductionTypeId { get; set; }
        public Nullable<int> SatetId { get; set; }
        public string City { get; set; }
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> ReagentCode { get; set; }
        public int UserInfoId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    }
}
