//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.33440.
// 
#pragma warning disable 1591

namespace AlmaCMS.ir.smsran {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendSMSSoap", Namespace="http://tempuri.org/")]
    public partial class SendSMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CHECK_CREDITOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Sms1OperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Sms2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Sms3OperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Sms4OperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Sms5OperationCompleted;
        
        private System.Threading.SendOrPostCallback SEND_SMS_STATUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SEND_SMS_STATUS2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Receive_SmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Receive_Sms2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendSMS() {
            this.Url = global::AlmaCMS.Properties.Settings.Default.AlmaCMS_ir_smsran_SendSMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CHECK_CREDITCompletedEventHandler CHECK_CREDITCompleted;
        
        /// <remarks/>
        public event Send_Sms1CompletedEventHandler Send_Sms1Completed;
        
        /// <remarks/>
        public event Send_Sms2CompletedEventHandler Send_Sms2Completed;
        
        /// <remarks/>
        public event Send_Sms3CompletedEventHandler Send_Sms3Completed;
        
        /// <remarks/>
        public event Send_Sms4CompletedEventHandler Send_Sms4Completed;
        
        /// <remarks/>
        public event Send_Sms5CompletedEventHandler Send_Sms5Completed;
        
        /// <remarks/>
        public event SEND_SMS_STATUSCompletedEventHandler SEND_SMS_STATUSCompleted;
        
        /// <remarks/>
        public event SEND_SMS_STATUS2CompletedEventHandler SEND_SMS_STATUS2Completed;
        
        /// <remarks/>
        public event Receive_SmsCompletedEventHandler Receive_SmsCompleted;
        
        /// <remarks/>
        public event Receive_Sms2CompletedEventHandler Receive_Sms2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CHECK_CREDIT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal CHECK_CREDIT(string USERNAME, string PASSWORD) {
            object[] results = this.Invoke("CHECK_CREDIT", new object[] {
                        USERNAME,
                        PASSWORD});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void CHECK_CREDITAsync(string USERNAME, string PASSWORD) {
            this.CHECK_CREDITAsync(USERNAME, PASSWORD, null);
        }
        
        /// <remarks/>
        public void CHECK_CREDITAsync(string USERNAME, string PASSWORD, object userState) {
            if ((this.CHECK_CREDITOperationCompleted == null)) {
                this.CHECK_CREDITOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCHECK_CREDITOperationCompleted);
            }
            this.InvokeAsync("CHECK_CREDIT", new object[] {
                        USERNAME,
                        PASSWORD}, this.CHECK_CREDITOperationCompleted, userState);
        }
        
        private void OnCHECK_CREDITOperationCompleted(object arg) {
            if ((this.CHECK_CREDITCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CHECK_CREDITCompleted(this, new CHECK_CREDITCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Sms1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Sms1(string USERNAME, string PASSWORD, string TO, string TEXT) {
            object[] results = this.Invoke("Send_Sms1", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        TEXT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Sms1Async(string USERNAME, string PASSWORD, string TO, string TEXT) {
            this.Send_Sms1Async(USERNAME, PASSWORD, TO, TEXT, null);
        }
        
        /// <remarks/>
        public void Send_Sms1Async(string USERNAME, string PASSWORD, string TO, string TEXT, object userState) {
            if ((this.Send_Sms1OperationCompleted == null)) {
                this.Send_Sms1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Sms1OperationCompleted);
            }
            this.InvokeAsync("Send_Sms1", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        TEXT}, this.Send_Sms1OperationCompleted, userState);
        }
        
        private void OnSend_Sms1OperationCompleted(object arg) {
            if ((this.Send_Sms1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Sms1Completed(this, new Send_Sms1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Sms2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Sms2(string USERNAME, string PASSWORD, string TO, string TEXT, int API, bool API_CHANGE_ALLOW) {
            object[] results = this.Invoke("Send_Sms2", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Sms2Async(string USERNAME, string PASSWORD, string TO, string TEXT, int API, bool API_CHANGE_ALLOW) {
            this.Send_Sms2Async(USERNAME, PASSWORD, TO, TEXT, API, API_CHANGE_ALLOW, null);
        }
        
        /// <remarks/>
        public void Send_Sms2Async(string USERNAME, string PASSWORD, string TO, string TEXT, int API, bool API_CHANGE_ALLOW, object userState) {
            if ((this.Send_Sms2OperationCompleted == null)) {
                this.Send_Sms2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Sms2OperationCompleted);
            }
            this.InvokeAsync("Send_Sms2", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW}, this.Send_Sms2OperationCompleted, userState);
        }
        
        private void OnSend_Sms2OperationCompleted(object arg) {
            if ((this.Send_Sms2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Sms2Completed(this, new Send_Sms2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Sms3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Sms3(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW) {
            object[] results = this.Invoke("Send_Sms3", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        FROM,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Sms3Async(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW) {
            this.Send_Sms3Async(USERNAME, PASSWORD, TO, FROM, TEXT, API, API_CHANGE_ALLOW, null);
        }
        
        /// <remarks/>
        public void Send_Sms3Async(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, object userState) {
            if ((this.Send_Sms3OperationCompleted == null)) {
                this.Send_Sms3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Sms3OperationCompleted);
            }
            this.InvokeAsync("Send_Sms3", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        FROM,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW}, this.Send_Sms3OperationCompleted, userState);
        }
        
        private void OnSend_Sms3OperationCompleted(object arg) {
            if ((this.Send_Sms3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Sms3Completed(this, new Send_Sms3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Sms4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Sms4(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, int FLASH, bool Internation) {
            object[] results = this.Invoke("Send_Sms4", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        FROM,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW,
                        FLASH,
                        Internation});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Sms4Async(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, int FLASH, bool Internation) {
            this.Send_Sms4Async(USERNAME, PASSWORD, TO, FROM, TEXT, API, API_CHANGE_ALLOW, FLASH, Internation, null);
        }
        
        /// <remarks/>
        public void Send_Sms4Async(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, int FLASH, bool Internation, object userState) {
            if ((this.Send_Sms4OperationCompleted == null)) {
                this.Send_Sms4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Sms4OperationCompleted);
            }
            this.InvokeAsync("Send_Sms4", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        FROM,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW,
                        FLASH,
                        Internation}, this.Send_Sms4OperationCompleted, userState);
        }
        
        private void OnSend_Sms4OperationCompleted(object arg) {
            if ((this.Send_Sms4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Sms4Completed(this, new Send_Sms4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Sms5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Sms5(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, int FLASH, System.DateTime DATE, bool Internation) {
            object[] results = this.Invoke("Send_Sms5", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        FROM,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW,
                        FLASH,
                        DATE,
                        Internation});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Sms5Async(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, int FLASH, System.DateTime DATE, bool Internation) {
            this.Send_Sms5Async(USERNAME, PASSWORD, TO, FROM, TEXT, API, API_CHANGE_ALLOW, FLASH, DATE, Internation, null);
        }
        
        /// <remarks/>
        public void Send_Sms5Async(string USERNAME, string PASSWORD, string TO, string FROM, string TEXT, int API, bool API_CHANGE_ALLOW, int FLASH, System.DateTime DATE, bool Internation, object userState) {
            if ((this.Send_Sms5OperationCompleted == null)) {
                this.Send_Sms5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Sms5OperationCompleted);
            }
            this.InvokeAsync("Send_Sms5", new object[] {
                        USERNAME,
                        PASSWORD,
                        TO,
                        FROM,
                        TEXT,
                        API,
                        API_CHANGE_ALLOW,
                        FLASH,
                        DATE,
                        Internation}, this.Send_Sms5OperationCompleted, userState);
        }
        
        private void OnSend_Sms5OperationCompleted(object arg) {
            if ((this.Send_Sms5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Sms5Completed(this, new Send_Sms5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SEND_SMS_STATUS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SEND_SMS_STATUS(string USERNAME, string PASSWORD, int SEND_ID, string TO) {
            object[] results = this.Invoke("SEND_SMS_STATUS", new object[] {
                        USERNAME,
                        PASSWORD,
                        SEND_ID,
                        TO});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SEND_SMS_STATUSAsync(string USERNAME, string PASSWORD, int SEND_ID, string TO) {
            this.SEND_SMS_STATUSAsync(USERNAME, PASSWORD, SEND_ID, TO, null);
        }
        
        /// <remarks/>
        public void SEND_SMS_STATUSAsync(string USERNAME, string PASSWORD, int SEND_ID, string TO, object userState) {
            if ((this.SEND_SMS_STATUSOperationCompleted == null)) {
                this.SEND_SMS_STATUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSEND_SMS_STATUSOperationCompleted);
            }
            this.InvokeAsync("SEND_SMS_STATUS", new object[] {
                        USERNAME,
                        PASSWORD,
                        SEND_ID,
                        TO}, this.SEND_SMS_STATUSOperationCompleted, userState);
        }
        
        private void OnSEND_SMS_STATUSOperationCompleted(object arg) {
            if ((this.SEND_SMS_STATUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SEND_SMS_STATUSCompleted(this, new SEND_SMS_STATUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SEND_SMS_STATUS2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SEND_SMS_STATUS2(string USERNAME, string PASSWORD, int SEND_ID, string TO, out string API_Exit) {
            object[] results = this.Invoke("SEND_SMS_STATUS2", new object[] {
                        USERNAME,
                        PASSWORD,
                        SEND_ID,
                        TO});
            API_Exit = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SEND_SMS_STATUS2Async(string USERNAME, string PASSWORD, int SEND_ID, string TO) {
            this.SEND_SMS_STATUS2Async(USERNAME, PASSWORD, SEND_ID, TO, null);
        }
        
        /// <remarks/>
        public void SEND_SMS_STATUS2Async(string USERNAME, string PASSWORD, int SEND_ID, string TO, object userState) {
            if ((this.SEND_SMS_STATUS2OperationCompleted == null)) {
                this.SEND_SMS_STATUS2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSEND_SMS_STATUS2OperationCompleted);
            }
            this.InvokeAsync("SEND_SMS_STATUS2", new object[] {
                        USERNAME,
                        PASSWORD,
                        SEND_ID,
                        TO}, this.SEND_SMS_STATUS2OperationCompleted, userState);
        }
        
        private void OnSEND_SMS_STATUS2OperationCompleted(object arg) {
            if ((this.SEND_SMS_STATUS2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SEND_SMS_STATUS2Completed(this, new SEND_SMS_STATUS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Receive_Sms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Receive_Sms(string USERNAME, string PASSWORD, string NUMBER) {
            object[] results = this.Invoke("Receive_Sms", new object[] {
                        USERNAME,
                        PASSWORD,
                        NUMBER});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Receive_SmsAsync(string USERNAME, string PASSWORD, string NUMBER) {
            this.Receive_SmsAsync(USERNAME, PASSWORD, NUMBER, null);
        }
        
        /// <remarks/>
        public void Receive_SmsAsync(string USERNAME, string PASSWORD, string NUMBER, object userState) {
            if ((this.Receive_SmsOperationCompleted == null)) {
                this.Receive_SmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceive_SmsOperationCompleted);
            }
            this.InvokeAsync("Receive_Sms", new object[] {
                        USERNAME,
                        PASSWORD,
                        NUMBER}, this.Receive_SmsOperationCompleted, userState);
        }
        
        private void OnReceive_SmsOperationCompleted(object arg) {
            if ((this.Receive_SmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Receive_SmsCompleted(this, new Receive_SmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Receive_Sms2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result_Receive[] Receive_Sms2(string USERNAME, string PASSWORD, string NUMBER) {
            object[] results = this.Invoke("Receive_Sms2", new object[] {
                        USERNAME,
                        PASSWORD,
                        NUMBER});
            return ((Result_Receive[])(results[0]));
        }
        
        /// <remarks/>
        public void Receive_Sms2Async(string USERNAME, string PASSWORD, string NUMBER) {
            this.Receive_Sms2Async(USERNAME, PASSWORD, NUMBER, null);
        }
        
        /// <remarks/>
        public void Receive_Sms2Async(string USERNAME, string PASSWORD, string NUMBER, object userState) {
            if ((this.Receive_Sms2OperationCompleted == null)) {
                this.Receive_Sms2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceive_Sms2OperationCompleted);
            }
            this.InvokeAsync("Receive_Sms2", new object[] {
                        USERNAME,
                        PASSWORD,
                        NUMBER}, this.Receive_Sms2OperationCompleted, userState);
        }
        
        private void OnReceive_Sms2OperationCompleted(object arg) {
            if ((this.Receive_Sms2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Receive_Sms2Completed(this, new Receive_Sms2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result_Receive {
        
        private int idField;
        
        private string fromField;
        
        private string toField;
        
        private string mESSAGEField;
        
        private System.DateTime dATEField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string TO {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CHECK_CREDITCompletedEventHandler(object sender, CHECK_CREDITCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CHECK_CREDITCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CHECK_CREDITCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Send_Sms1CompletedEventHandler(object sender, Send_Sms1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Sms1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Sms1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Send_Sms2CompletedEventHandler(object sender, Send_Sms2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Sms2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Sms2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Send_Sms3CompletedEventHandler(object sender, Send_Sms3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Sms3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Sms3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Send_Sms4CompletedEventHandler(object sender, Send_Sms4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Sms4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Sms4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Send_Sms5CompletedEventHandler(object sender, Send_Sms5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Sms5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Sms5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SEND_SMS_STATUSCompletedEventHandler(object sender, SEND_SMS_STATUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SEND_SMS_STATUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SEND_SMS_STATUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SEND_SMS_STATUS2CompletedEventHandler(object sender, SEND_SMS_STATUS2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SEND_SMS_STATUS2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SEND_SMS_STATUS2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string API_Exit {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Receive_SmsCompletedEventHandler(object sender, Receive_SmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Receive_SmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Receive_SmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Receive_Sms2CompletedEventHandler(object sender, Receive_Sms2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Receive_Sms2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Receive_Sms2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result_Receive[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result_Receive[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591